### ISSUE TITLE
✨ [Feature]: head是否支持修改为中文场景

### ISSUE THREAD

**Issue by walkerleee** [opentiny/fluent-editor#57]
### What problem does this feature solve

![image](https://github.com/user-attachments/assets/38131f39-680a-4823-81d6-eac0c4164ad3)

能不能支持修改为中文场景

### What does the proposed API look like

 toolbar 的配置  [{ header: [1, 2, 3, 4, 5, 6, false] }]

### What is your project name

·

**Comment by kagol** [comment]
@walkerleee 可以通过CSS自己控制。

示例代码：

```css
.ql-snow .ql-picker.ql-header .ql-picker-item[data-value="1"]:before {
    content: "标题1";
}
```
